version: 2.1

jobs:
  ecr-build:
    filters:
      tags:
        only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
      branches:
        ignore: /.*/
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Display Env
          command: env
  
workflows:
  aws-lambda-deploy:
    jobs:
      - ecr-build
