version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  aws-lambda-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
          repo: $AWS_ECR_REPOSITORY
          tag: "${CIRCLE_SHA1},latest"
          path: lambda
