version: 2.1

workflows:
  aws-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^lambda\/v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
          working_directory: ~/repo
          # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
          # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
          docker:
            - image: circleci/golang:1.15.8
          # Add steps to the job
          # See: https://circleci.com/docs/2.0/configuration-reference/#steps
          steps:
            - checkout
            - restore_cache:
                keys:
                  - go-mod-v4-{{ checksum "go.sum" }}
            - run:
                name: Display Env
                command: env
            - run:
                name: Install Dependencies
                command: go mod download
            - save_cache:
                key: go-mod-v4-{{ checksum "go.sum" }}
                paths:
                  - "/go/pkg/mod"
            - run:
                name: Run tests
                command: |
                  mkdir -p /tmp/test-reports
                  gotestsum --junitfile /tmp/test-reports/unit-tests.xml
            - store_test_results:
                path: /tmp/test-reports
